export type LandingLanguage = 'en' | 'mr';

export const localizedCopy = {
  en: {
    brandDescriptor: 'A Samavet product',
    portalCta: 'Start collecting',
    portalPreviewCta: 'See the portal',
    blog: 'Blog',
    menu: 'Toggle menu',
    theme: 'Toggle color theme',
    language: 'Language selection',
    heroEyebrow: 'Built for mandals, temples & trusts',
    heroTitle: ['Digital Pawati Trusted', 'by', 'for fast & Transparent', 'Vargani Collection'],
    heroAudienceWords: ['Mandal', 'Mandir', 'Trust', 'Organisation'],
    heroDescription: 'ePawati replaces the receipt book with digital Pawati and Vargani software your whole committee can run — paperless, fast and reliable. One destination to manage every donation, donor and volunteer.',
    receiptSent: 'Receipt #2451 sent',
    receiptDonor: 'Sneha Kulkarni · WhatsApp delivered',
    collectionSource: 'Pandal QR',
    collectedToday: 'collected today',
    stats: [
      { value: '300+', label: 'Temples targeted' },
      { value: '50+', label: 'Mandals registered' },
      { value: '5,000+', label: 'Slips generated' },
    ],
    featuresEyebrow: 'Everything in one place',
    featuresTitle: 'The whole utsav, handled.',
    featuresDescription: 'From receipt sharing to committee records, ePawati gives mandals, trusts, temples and organisations one clean system to manage every important document.',
    features: [
      ['Instant digital receipts', 'Create and share branded receipts the moment a donation is recorded, so every donor gets a clear acknowledgement without paper books or manual follow-ups.'],
      ['Mandal, trust, temple and organisation management', 'Manage members, groups, roles, yearly records and collections from one secure portal built for real community committees.'],
      ['Audit-ready PDF exports', 'Download clean PDF reports for collections, donors and committee review whenever trustees, admins or auditors need verified records.'],
      ['3D flipbook for organisation documents', 'Upload your organisation PDFs and turn them into interactive 3D flipbooks that logged-in members can read directly inside the portal.'],
      ['Samavet Murti — digital murti booking and selling', 'List, book and sell murtis through a digital platform with integrated payments, automatic slip generation sent to WhatsApp, and a full dashboard to manage inventory, orders and customers.'],
    ],
    portalEyebrow: 'Inside the portal',
    portalTitle: 'One screen your committee will actually use.',
    portalUrlLabel: 'app.epawati.in / shree-ganesh-mandal',
    portalTotalLabel: 'Collected this utsav',
    portalTotal: '₹8,42,310',
    portalGrowth: '+18% vs last year',
    chartLabel: 'Collections by day',
    portalTabs: ['Collections', 'Donors', 'Reports'],
    portalRows: {
      collections: [
        ['Sneha Kulkarni', 'Ward 4 · UPI', '₹2,100'],
        ['Deshmukh Family', 'Ward 2 · UPI', '₹5,001'],
        ['Rohit Pawar', 'Pandal QR', '₹501'],
        ['Anonymous', 'Online link', '₹1,100'],
        ['Shree Traders', 'Sponsor', '₹25,000'],
      ],
      donors: [
        ['Deshmukh Family', '4 donations', '₹18,502'],
        ['Sneha Kulkarni', '3 donations', '₹7,101'],
        ['Shree Traders', 'Annual sponsor', '₹25,000'],
        ['Rohit Pawar', '2 donations', '₹1,002'],
        ['Anonymous donors', '86 donations', '₹42,340'],
      ],
      reports: [
        ['Daily collection', 'Updated today', 'PDF'],
        ['Volunteer summary', '18 collectors', 'XLS'],
        ['Donor statement', '1,284 records', 'CSV'],
        ['80G summary', 'Current utsav', 'PDF'],
        ['Bank reconciliation', 'Up to date', 'XLS'],
      ],
    },
    howEyebrow: 'Live before the aarti',
    howTitle: 'From setup to collection in three clear steps.',
    howSteps: [
      ['Set up your mandal', 'Add your trust name, logo and bank details once. Your collection page is live in minutes.'],
      ['Share your link or QR', 'Print the QR for the pandal, drop the link in your WhatsApp groups. Donors need no app.'],
      ['Track everything live', 'Receipts go out automatically while you watch collections, volunteers and reports update live.'],
    ],
    compareTitle: 'Paper never stood a chance.',
    oldWayTitle: 'The receipt book way',
    oldWay: ['Receipt books that run out mid-visarjan', 'Cash counted twice and still short', 'Donor names lost between years', 'Reports built from photos of registers', 'No idea who collected what'],
    newWayTitle: 'The ePawati way',
    newWay: ['Receipts sent the second money lands', 'Every rupee reconciled automatically', 'Donor history carried forward forever', 'One-click statements for the committee', 'Volunteer-wise totals, live'],
    faqEyebrow: 'Straight answers',
    faqTitle: 'Questions the committee always asks.',
    faqs: [
      ['What does ePawati cost?', 'There is no setup fee or annual licence. Contact the Samavet team for the current transaction pricing that applies to your collection.'],
      ['How fast does money reach our bank account?', 'The typical settlement time is 0.5 hours. Exact timing can vary with bank processing schedules and holidays.'],
      ['Do donors need to install anything?', 'No. Donors can open your collection link or scan the pandal QR, pay with their preferred UPI app, and receive the receipt directly.'],
      ['Can we still record cash donations?', 'Yes. Authorised volunteers can record cash donations in the portal so every contribution remains part of the same report.'],
      ['Who owns the donor data?', 'Your organisation controls its donor records. Role-based access keeps collection work available to volunteers while trustee controls remain protected.'],
    ],
    contactEyebrow: 'Contact Samavet',
    contactTitle: 'Tell us what your organisation needs.',
    contactDescription: 'Share a few details and your email app will open a prepared message to our team.',
    contactFields: {
      organization: 'Organisation / trust / mandal name',
      email: 'Email address',
      address: 'Address',
      phone: 'Phone number (optional)',
      message: 'Message',
    },
    contactPlaceholders: {
      organization: 'Shree Ganesh Mandal',
      email: 'you@organisation.org',
      address: 'Area, city, state',
      phone: '+91 98765 43210',
      message: 'How can Samavet help?',
    },
    contactSubmit: 'Send message',
    contactStatus: 'Your email app is opening with the prepared message.',
    contactThankYouTitle: 'Thank you for connecting with Samavet.',
    contactThankYouDescription: 'Your message has been sent. Our team will get back to you shortly.',
    contactEditForm: 'Edit your details',
    contactErrors: {
      organization: 'Enter your organisation name.',
      email: 'Enter a valid email address.',
      address: 'Enter your address.',
      phone: 'Enter a valid phone number or leave it blank.',
      message: 'Enter a short message.',
    },
    ctaTitle: 'Retire the receipt book this utsav.',
    ctaDescription: 'Set up your mandal or trust in minutes. No setup fee, no annual licence — just faster, cleaner collections.',
    footerDescription: 'Paperless donation management for trusts, temples and Ganapati mandals across India.',
    footerLocation: 'Pune, Maharashtra',
    copyright: 'Samavet. All rights reserved.',
  },
  mr: {
    brandDescriptor: 'समवेतचे उत्पादन',
    portalCta: 'संकलन सुरू करा',
    portalPreviewCta: 'पोर्टल पाहा',
    blog: 'ब्लॉग',
    menu: 'मेनू उघडा किंवा बंद करा',
    theme: 'रंगसंगती बदला',
    language: 'भाषा निवड',
    heroEyebrow: 'मंडळे, मंदिरे आणि ट्रस्टसाठी तयार',
    heroTitle: ['विश्वासार्ह डिजिटल पावती', '', 'जलद आणि पारदर्शक', 'वर्गणी संकलनासाठी'],
    heroAudienceWords: ['मंडळासाठी', 'मंदिरासाठी', 'ट्रस्टसाठी', 'संस्थेसाठी'],
    heroDescription: 'ई-पावती कागदी पावतीपुस्तकाऐवजी डिजिटल पावती आणि डिजिटल वर्गणी सॉफ्टवेअर देते, जे तुमच्या संपूर्ण समितीला सहज वापरता येते. प्रत्येक देणगी, देणगीदार आणि स्वयंसेवकासाठी एकच ठिकाण.',
    receiptSent: 'पावती #२४५१ पाठवली',
    receiptDonor: 'स्नेहा कुलकर्णी · व्हॉट्सअ‍ॅपवर पोहोचली',
    collectionSource: 'मंडप QR',
    collectedToday: 'आजचे संकलन',
    stats: [
      { value: '३००+', label: 'लक्ष्यित मंदिरे' },
      { value: '५०+', label: 'नोंदणीकृत मंडळे' },
      { value: '५,०००+', label: 'तयार झालेल्या पावत्या' },
    ],
    featuresEyebrow: 'सर्व काही एका ठिकाणी',
    featuresTitle: 'संपूर्ण उत्सवाचे व्यवस्थापन.',
    featuresDescription: 'पावती शेअरिंगपासून समितीच्या नोंदींपर्यंत, ई-पावती मंडळे, ट्रस्ट, मंदिरे आणि संस्थांसाठी सर्व महत्त्वाची कागदपत्रे सांभाळणारी एक स्वच्छ प्रणाली देते.',
    features: [
      ['त्वरित डिजिटल पावत्या', 'देणगीची नोंद होताच ब्रँडेड पावती तयार करून शेअर करा, त्यामुळे देणगीदाराला कागदी पुस्तकांशिवाय आणि मॅन्युअल फॉलो-अपशिवाय स्पष्ट पावती मिळते.'],
      ['मंडळ, ट्रस्ट, मंदिर आणि संस्था व्यवस्थापन', 'सदस्य, गट, भूमिका, वार्षिक नोंदी आणि संकलन एका सुरक्षित पोर्टलमधून व्यवस्थापित करा, जे प्रत्यक्ष समितीच्या कामासाठी तयार आहे.'],
      ['ऑडिटसाठी तयार PDF एक्सपोर्ट', 'ट्रस्टी, अ‍ॅडमिन किंवा ऑडिटरला पडताळलेल्या नोंदी हव्या असताना संकलन, देणगीदार आणि समिती आढाव्यासाठी स्वच्छ PDF अहवाल डाउनलोड करा.'],
      ['संस्थेच्या कागदपत्रांसाठी 3D फ्लिपबुक', 'तुमच्या संस्थेचे PDF अपलोड करा आणि त्यांना इंटरॅक्टिव्ह 3D फ्लिपबुकमध्ये बदला, जे लॉगिन केलेले सदस्य पोर्टलमध्ये थेट वाचू शकतात.'],
      ['समवेत मूर्ती — डिजिटल मूर्ती बुकिंग आणि विक्री', 'एकीकृत पेमेंट, व्हॉट्सअ‍ॅपवर पाठवलेल्या आपोआप तयार होणाऱ्या पावत्या, आणि इन्व्हेंटरी, ऑर्डर व ग्राहकांचे संपूर्ण डॅशबोर्डसह मूर्ती डिजिटल प्लॅटफॉर्मवर यादी करा, बुक करा आणि विका.'],
    ],
    portalEyebrow: 'पोर्टलच्या आत',
    portalTitle: 'तुमची समिती खरोखर वापरेल अशी एक स्क्रीन.',
    portalUrlLabel: 'app.epawati.in / shree-ganesh-mandal',
    portalTotalLabel: 'या उत्सवातील संकलन',
    portalTotal: '₹८,४२,३१०',
    portalGrowth: 'मागील वर्षापेक्षा +१८%',
    chartLabel: 'दिवसानुसार संकलन',
    portalTabs: ['संकलन', 'देणगीदार', 'अहवाल'],
    portalRows: {
      collections: [['स्नेहा कुलकर्णी', 'प्रभाग ४ · UPI', '₹२,१००'], ['देशमुख कुटुंब', 'प्रभाग २ · UPI', '₹५,००१'], ['रोहित पवार', 'मंडप QR', '₹५०१'], ['निनावी', 'ऑनलाइन लिंक', '₹१,१००'], ['श्री ट्रेडर्स', 'प्रायोजक', '₹२५,०००']],
      donors: [['देशमुख कुटुंब', '४ देणग्या', '₹१८,५०२'], ['स्नेहा कुलकर्णी', '३ देणग्या', '₹७,१०१'], ['श्री ट्रेडर्स', 'वार्षिक प्रायोजक', '₹२५,०००'], ['रोहित पवार', '२ देणग्या', '₹१,००२'], ['निनावी देणगीदार', '८६ देणग्या', '₹४२,३४०']],
      reports: [['दैनिक संकलन', 'आज अद्ययावत', 'PDF'], ['स्वयंसेवक सारांश', '१८ संकलक', 'XLS'], ['देणगीदार स्टेटमेंट', '१,२८४ नोंदी', 'CSV'], ['80G सारांश', 'सध्याचा उत्सव', 'PDF'], ['बँक जुळवणी', 'अद्ययावत', 'XLS']],
    },
    howEyebrow: 'आरतीपूर्वीच लाइव्ह',
    howTitle: 'सेटअपपासून संकलनापर्यंत तीन सोप्या पायऱ्या.',
    howSteps: [['तुमचे मंडळ तयार करा', 'ट्रस्टचे नाव, लोगो आणि बँक तपशील एकदाच जोडा. तुमचे संकलन पेज काही मिनिटांत लाइव्ह होते.'], ['लिंक किंवा QR शेअर करा', 'मंडपासाठी QR प्रिंट करा आणि व्हॉट्सअ‍ॅप ग्रुपमध्ये लिंक पाठवा. देणगीदारांना कोणतेही अ‍ॅप लागत नाही.'], ['सर्व काही लाइव्ह पाहा', 'पावत्या आपोआप पाठवल्या जातात आणि संकलन, स्वयंसेवक व अहवाल रिअल टाइममध्ये अद्ययावत होतात.']],
    compareTitle: 'कागदी पावतीपुस्तक आता मागे पडले.',
    oldWayTitle: 'पावतीपुस्तकाची पद्धत',
    oldWay: ['विसर्जनाच्या गर्दीत संपणारी पावतीपुस्तके', 'दोनदा मोजूनही कमी पडणारी रोकड', 'वर्षानुवर्षे हरवणारी देणगीदारांची नावे', 'रजिस्टरच्या फोटोंवरून तयार होणारे अहवाल', 'कोणी किती संकलन केले याची माहिती नाही'],
    newWayTitle: 'ई-पावतीची पद्धत',
    newWay: ['रक्कम मिळताच त्वरित पावती', 'प्रत्येक रुपयाची आपोआप जुळवणी', 'देणगीदारांचा इतिहास कायम उपलब्ध', 'समितीसाठी एका क्लिकमध्ये स्टेटमेंट', 'स्वयंसेवकनिहाय लाइव्ह एकूण रक्कम'],
    faqEyebrow: 'स्पष्ट उत्तरे',
    faqTitle: 'समिती नेहमी विचारते असे प्रश्न.',
    faqs: [['ई-पावतीची किंमत किती आहे?', 'सेटअप शुल्क किंवा वार्षिक परवाना नाही. तुमच्या संकलनाला लागू होणाऱ्या सध्याच्या व्यवहार शुल्कासाठी समवेत टीमशी संपर्क साधा.'], ['पैसे आमच्या बँक खात्यात किती लवकर येतात?', 'सामान्य सेटलमेंट वेळ ०.५ तास आहे. बँकेचे वेळापत्रक आणि सुट्ट्यांनुसार अचूक वेळ बदलू शकते.'], ['देणगीदारांना अ‍ॅप इन्स्टॉल करावे लागते का?', 'नाही. देणगीदार लिंक उघडू शकतात किंवा मंडपातील QR स्कॅन करून त्यांच्या पसंतीच्या UPI अ‍ॅपमधून पैसे भरू शकतात.'], ['रोख देणगीची नोंद करता येते का?', 'होय. अधिकृत स्वयंसेवक पोर्टलमध्ये रोख देणगी नोंदवू शकतात, त्यामुळे प्रत्येक देणगी एकाच अहवालात राहते.'], ['देणगीदारांच्या डेटाची मालकी कोणाची?', 'देणगीदारांच्या नोंदींवर तुमच्या संस्थेचे नियंत्रण असते. भूमिकेनुसार प्रवेश दिल्यामुळे ट्रस्टींचे नियंत्रण सुरक्षित राहते.']],
    contactEyebrow: 'समवेतशी संपर्क',
    contactTitle: 'तुमच्या संस्थेला काय हवे आहे ते सांगा.',
    contactDescription: 'काही तपशील शेअर करा. आमच्या टीमसाठी तयार केलेला संदेश तुमच्या ईमेल अ‍ॅपमध्ये उघडेल.',
    contactFields: {
      organization: 'संस्था / ट्रस्ट / मंडळाचे नाव',
      email: 'ईमेल पत्ता',
      address: 'पत्ता',
      phone: 'फोन नंबर (ऐच्छिक)',
      message: 'संदेश',
    },
    contactPlaceholders: {
      organization: 'श्री गणेश मंडळ',
      email: 'you@organisation.org',
      address: 'परिसर, शहर, राज्य',
      phone: '+९१ ९८७६५ ४३२१०',
      message: 'समवेत तुम्हाला कशी मदत करू शकते?',
    },
    contactSubmit: 'संदेश पाठवा',
    contactStatus: 'तयार संदेशासह तुमचे ईमेल अ‍ॅप उघडत आहे.',
    contactThankYouTitle: 'समवेतशी संपर्क केल्याबद्दल धन्यवाद.',
    contactThankYouDescription: 'तुमचा संदेश पाठवला आहे. आमची टीम लवकरच तुमच्याशी संपर्क करेल.',
    contactEditForm: 'तुमचे तपशील संपादित करा',
    contactErrors: {
      organization: 'तुमच्या संस्थेचे नाव लिहा.',
      email: 'वैध ईमेल पत्ता लिहा.',
      address: 'तुमचा पत्ता लिहा.',
      phone: 'वैध फोन नंबर लिहा किंवा हे रिकामे ठेवा.',
      message: 'एक छोटा संदेश लिहा.',
    },
    ctaTitle: 'या उत्सवात पावतीपुस्तकाला निरोप द्या.',
    ctaDescription: 'तुमचे मंडळ किंवा ट्रस्ट काही मिनिटांत तयार करा. सेटअप शुल्क नाही, वार्षिक परवाना नाही — फक्त अधिक वेगवान आणि स्वच्छ संकलन.',
    footerDescription: 'भारतभरातील ट्रस्ट, मंदिरे आणि गणपती मंडळांसाठी पेपरलेस देणगी व्यवस्थापन.',
    footerLocation: 'पुणे, महाराष्ट्र',
    copyright: 'समवेत. सर्व हक्क राखीव.',
  },
} as const;

export type LandingCopy = (typeof localizedCopy)[LandingLanguage];
